DROP DATABASE IF EXISTS blogs;

CREATE DATABASE IF NOT EXISTS blogs;

CREATE TABLE IF NOT EXISTS blogs.posts(
	post_id INT PRIMARY KEY AUTO_INCREMENT,
    create_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(25) NOT NULL,
    content VARCHAR(50) NOT NULL

) ENGINE=InnoDB AUTO_INCREMENT=1;
